### ISSUE TITLE
Couldn't read partition table

### ISSUE THREAD

**Issue by DevHamid** [Diva-Room/DivaRelease#1]
![image](https://user-images.githubusercontent.com/13690753/215618638-b6c7cfda-cf44-455a-ad11-c8793dcb8c7e.png)

I already try on my wayne, but always say error like this. 
Also i already flash Latest stable MIUI China ROM also same, what's going on?
I don't know this phone have original partition table or not.

**Comment by DevHamid** [comment]
![image](https://user-images.githubusercontent.com/13690753/215626019-cd6c8bef-c39b-47d2-b4b5-7d91a47200f1.png)
![image](https://user-images.githubusercontent.com/13690753/215626053-84b5233a-7b7b-4c7f-9f37-38204ed883cb.png)

Here's the log i get from recovery

**Comment by xiaoleGun** [comment]
Format data
